linkPrefix = "mirai-poc"
name = "Mirai"
license = "MIT"
version = "1.0.0"
description = "A decentralized marketplace for books"
homepage = "https://github.com/joshma91/mirai-poc"
author = "Josh Ma"
buildTime = 2018-11-24T20:27:14.317Z
target = "scripts/doxity"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"
out = "docs"

[interaction]